//-----------------------------------------------------------------------
// <auto-generated />
//-----------------------------------------------------------------------
using System;

namespace WebApplication2.Models.CodeList
{
    public static class UserTableActions
    {
        /// <summary>
        /// Action adds new user
        /// LABEL
        /// </summary>
        public const string NEW_USER = "NEW_USER";

        /// <summary>
        /// Action edits user
        /// LABEL
        /// </summary>
        public const string EDIT_USER = "EDIT_USER";

        /// <summary>
        /// Action edits user
        /// LABEL
        /// </summary>
        public const string EDIT_PROFILE = "EDIT_PROFILE";

        /// <summary>
        /// Action locks user
        /// LABEL
        /// </summary>
        public const string LOCK_USER = "LOCK_USER";


        /// <summary>
        /// Action unlocks user
        /// LABEL
        /// </summary>
        public const string UNLOCK_USER = "UNLOCK_USER";

        /// <summary>
        /// Action syncs domain users
        /// LABEL
        /// </summary>
        public const string SYNC_DOMAIN_USERS = "SYNC_DOMAIN_USERS";

        /// <summary>
        /// Action edits user
        /// LABEL
        /// </summary>
        public const string ADD_ROLE_TO_USER = "ADD_ROLE_TO_USER";

        /// <summary>
        /// Action edits user
        /// LABEL
        /// </summary>
        public const string REMOVE_ROLE_FROM_USER = "REMOVE_ROLE_FROM_USER";

        /// <summary>
        /// Action edits user
        /// LABEL
        /// </summary>
        public const string EDIT_ROLES = "EDIT_ROLES";

        /// <summary>
        /// Action adds new user
        /// LABEL
        /// </summary>
        public const string NEW_ROLE = "NEW_ROLE";

        /// <summary>
        /// Action edits user
        /// LABEL
        /// </summary>
        public const string EDIT_ROLE = "EDIT_ROLE";

        /// <summary>
        /// Action edits user
        /// LABEL
        /// </summary>
        public const string DISCARD_ROLE = "DISCARD_ROLE";

        /// <summary>
        /// Action edits user
        /// LABEL
        /// </summary>
        public const string ADD_PAGE_PERMISSION = "ADD_PAGE_PERMISSION";

        /// <summary>
        /// Action edits user
        /// LABEL
        /// </summary>
        public const string REMOVE_PAGE_PERMISSION = "REMOVE_PAGE_PERMISSION";

        /// <summary>
        /// Action edits user
        /// LABEL
        /// </summary>
        public const string ADD_NAVIGATION_GROUP_PERMISSION = "ADD_NAVIGATION_GROUP_PERMISSION";

        /// <summary>
        /// Action edits user
        /// LABEL
        /// </summary>
        public const string REMOVE_NAVIGATION_GROUP_PERMISSION = "REMOVE_NAVIGATION_GROUP_PERMISSION";

    }
}

