

//-----------------------------------------------------------------------
// <auto-generated />
//-----------------------------------------------------------------------
using System;

namespace WebApplication2.Models.CodeList
{
    public static class UserApplicationMessages
    {
        public const string an_com_NEW_USER_key = "an_com_NEW_USER_key";

        public const string USERNAME_NOT_UNIQUE = "s:usernameNotUnique";

        public const string INCORRECT_PASSWORD = "s:incorrectOldPassword";

        public const string PASSWORDS_ARE_NOT_SAME = "s:passwordNotSame";

        public const string UNMEET_PASSWORD_REQUIREMENTS = "s:newPasswordNotStrong";

        public const string USER_ALREADY_HAS_THIS_ROLE = "s:userAlreadyInRole";

        public const string ROLE_NAME_NOT_UNIQUE = "s:roleNameNotUnique";

        public const string MAPPING_EXISTS = "s:mappingAlreadyExists";
    }
}
