//-----------------------------------------------------------------------
// <auto-generated />
//-----------------------------------------------------------------------
using System;

namespace WebApplication2.Models.CodeList
{
    public static class UtlTableActions
    {
        /// <summary>
        /// Action adds new user
        /// LABEL
        /// </summary>
        public const string EDIT_APPLICATION_SETTINGS = "EDIT_APPLICATION_SETTINGS";
    }
}

