//-----------------------------------------------------------------------
// <auto-generated />
//-----------------------------------------------------------------------
using System;

namespace WebApplication2.Models.CodeList
{
    public static class UserRecordTypes
    {
        public const string USERS = "USERS";

        public const string ROLES = "ROLES";

        public const string USER_ROLES = "USER_ROLES";

        public const string ROLE_PAGE_PERMISSIONS = "ROLE_PAGE_PERMISSIONS";

        public const string ROLE_NAVIGATION_GROUP_PERMISSIONS = "ROLE_NAVIGATION_GROUP_PERMISSIONS";

    }
}