

//-----------------------------------------------------------------------
// <auto-generated />
//-----------------------------------------------------------------------
using System;

namespace WebApplication2.Models.CodeList
{
    public static class UserApplicationMessages
    {
        public const string an_com_NEW_USER_key = "an_com_NEW_USER_key";

        public const string USERNAME_NOT_UNIQUE = "Username is not unique.";

        public const string USER_ALREADY_HAS_THIS_ROLE = "Username already has this role.";

        public const string ROLE_NAME_NOT_UNIQUE = "Name is not unique.";

        public const string MAPPING_EXISTS = "Mapping allready exists.";
    }
}
