//-----------------------------------------------------------------------
// <auto-generated />
//-----------------------------------------------------------------------
using System;

namespace WebApplication2.Models.CodeList
{
    public static class UtlRecordTypes
    {
        public const string APPLICATION_SETTINGS = "APPLICATION_SETTINGS";

    }
}